# plugins:
#   - jekyll-relative-links
# relative_links:
#   enabled: true
#   collections: true
# include:
#   - CONTRIBUTING.md
#   - README.md
#   - LICENSE.md
#   - COPYING.md
#   - CODE_OF_CONDUCT.md
#   - CONTRIBUTING.md
#   - ISSUE_TEMPLATE.md
#   - PULL_REQUEST_TEMPLATE.md

# highlighter: rouge
plugins:
    - jekyll-remote-theme

# remote_theme: just-the-docs/just-the-docs
# remote_theme: yous/whiteglass
# theme: just-the-docs
  

markdown: GFM
# markdown: GFM



markdown: kramdown
kramdown:
    input: GFM
    syntax_highlighter: rouge
    syntax_highlighter_opts:
        block:
            line_numbers: true
